//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiToGuardSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guard_user
    {
        public string UID { get; set; }
        public int RID { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public string AUTHORITY { get; set; }
        public string LOCATION { get; set; }
    }
}
